{% set version = "0.5-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-matrixmodels
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MatrixModels_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MatrixModels/MatrixModels_{{ version }}.tar.gz
  sha256: 3fc55bdfa5ab40c75bf395e90983d14c9715078c33c727c1658e4e1f36e43ea9

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix >=1.1_5
  run:
    - r-base
    - r-matrix >=1.1_5

test:
  commands:
    - $R -e "library('MatrixModels')"           # [not win]
    - "\"%R%\" -e \"library('MatrixModels')\""  # [win]

about:
  home: http://Matrix.R-forge.R-project.org/
  license: GPL-2.0-or-later
  summary: Modelling with sparse and dense 'Matrix' matrices, using modular prediction and response module classes.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
